"""
Pure config-to-output formatters.  No I/O, no prompts — easy to unit-test
and reused by both the CLI wizard and the static HTML wizard.
"""
from __future__ import annotations

from dataclasses import dataclass, field

VOLUME_NAME = "smb-mock-keytab"
NETWORK_NAME = "smb-mock-net"
KDC_CONTAINER = "smb-mock-kdc"
SAMBA_CONTAINER = "smb-mock-samba"


# ---------------------------------------------------------------------------
# Unified config model for the wizard
# ---------------------------------------------------------------------------
@dataclass
class WizardConfig:
    smb_hostname: str = "smbserver.smbtest.local"
    workgroup: str = "SMBTEST"
    realm: str = "SMBTEST.LOCAL"
    kdc_admin_password: str = "adminpass"
    enable_anonymous: bool = True
    enable_ntlm: bool = True
    enable_kerberos: bool = True
    smb_port: int = 445
    kdc_port: int = 88
    users: list[tuple[str, str]] = field(default_factory=list)
    shares: list[tuple[str, str, str]] = field(default_factory=list)
    trusts: list[tuple[str, str, str, str]] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------
def _bool(value: bool) -> str:
    return "true" if value else "false"


def _yaml_val(v: str) -> str:
    """Quote a YAML scalar if it contains characters that need quoting."""
    if any(c in v for c in ':#{}[]|>&*!,'):
        return f'"{v}"'
    return v


def _kdc_env(config: WizardConfig) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = [
        ("KRB5_REALM", config.realm),
        ("KRB5_ADMIN_PASSWORD", config.kdc_admin_password),
        ("SMB_HOSTNAME", config.smb_hostname),
    ]
    for i, (name, password) in enumerate(config.users):
        pairs.append((f"SMB_USER_{i}", f"{name}:{password}"))
    for i, (realm, kdc_host, secret, direction) in enumerate(config.trusts):
        pairs.append((f"SMB_TRUST_{i}", f"{realm}:{kdc_host}:{secret}:{direction}"))
    return pairs


def _samba_env(config: WizardConfig) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = [
        ("SMB_HOSTNAME", config.smb_hostname),
        ("SMB_WORKGROUP", config.workgroup),
        ("KRB5_REALM", config.realm),
        ("KDC_HOST", "kdc"),
        ("SMB_ENABLE_ANONYMOUS", _bool(config.enable_anonymous)),
        ("SMB_ENABLE_NTLM", _bool(config.enable_ntlm)),
        ("SMB_ENABLE_KERBEROS", _bool(config.enable_kerberos)),
    ]
    for i, (name, password) in enumerate(config.users):
        pairs.append((f"SMB_USER_{i}", f"{name}:{password}"))
    for i, (name, path, mode) in enumerate(config.shares):
        pairs.append((f"SMB_SHARE_{i}", f"{name}:{path}:{mode}"))
    for i, (realm, kdc_host, secret, direction) in enumerate(config.trusts):
        pairs.append((f"SMB_TRUST_{i}", f"{realm}:{kdc_host}:{secret}:{direction}"))
    return pairs


# ---------------------------------------------------------------------------
# Public formatters
# ---------------------------------------------------------------------------
def to_env_file(config: WizardConfig) -> str:
    """Return the content of a .env file for docker-compose."""
    lines = [
        "# smb-mock configuration — generated by smb-mock wizard",
        f"SMB_HOSTNAME={config.smb_hostname}",
        f"SMB_WORKGROUP={config.workgroup}",
        f"KRB5_REALM={config.realm}",
        f"KRB5_ADMIN_PASSWORD={config.kdc_admin_password}",
        f"SMB_ENABLE_ANONYMOUS={_bool(config.enable_anonymous)}",
        f"SMB_ENABLE_NTLM={_bool(config.enable_ntlm)}",
        f"SMB_ENABLE_KERBEROS={_bool(config.enable_kerberos)}",
        f"SMB_PORT={config.smb_port}",
        f"KDC_PORT={config.kdc_port}",
    ]
    for i, (name, password) in enumerate(config.users):
        lines.append(f"SMB_USER_{i}={name}:{password}")
    for i, (name, path, mode) in enumerate(config.shares):
        lines.append(f"SMB_SHARE_{i}={name}:{path}:{mode}")
    for i, (realm, kdc_host, secret, direction) in enumerate(config.trusts):
        lines.append(f"SMB_TRUST_{i}={realm}:{kdc_host}:{secret}:{direction}")
    return "\n".join(lines) + "\n"


def to_docker_run(config: WizardConfig) -> str:
    """Return a shell script of docker commands to start the stack."""

    def _env_flags(pairs: list[tuple[str, str]]) -> str:
        return " \\\n  ".join(f"-e {k}={v}" for k, v in pairs)

    kdc_envs = _env_flags(_kdc_env(config))
    samba_envs = _env_flags(_samba_env(config))

    return (
        "# smb-mock — generated by smb-mock wizard\n"
        "\n"
        f"docker volume create {VOLUME_NAME}\n"
        f"docker network create {NETWORK_NAME}\n"
        "\n"
        "# ── KDC ────────────────────────────────────────────────────────────\n"
        f"docker run -d \\\n"
        f"  --name {KDC_CONTAINER} \\\n"
        f"  --network {NETWORK_NAME} \\\n"
        f"  --network-alias kdc \\\n"
        f"  {kdc_envs} \\\n"
        f"  -p {config.kdc_port}:88/tcp \\\n"
        f"  -p {config.kdc_port}:88/udp \\\n"
        f"  -p 749:749/tcp \\\n"
        f"  -v {VOLUME_NAME}:/shared \\\n"
        f"  {KDC_CONTAINER}\n"
        "\n"
        "# ── Samba ───────────────────────────────────────────────────────────\n"
        f"docker run -d \\\n"
        f"  --name {SAMBA_CONTAINER} \\\n"
        f"  --network {NETWORK_NAME} \\\n"
        f"  --hostname {config.smb_hostname} \\\n"
        f"  {samba_envs} \\\n"
        f"  -p {config.smb_port}:445/tcp \\\n"
        f"  -v {VOLUME_NAME}:/shared \\\n"
        f"  {SAMBA_CONTAINER}\n"
    )


def to_compose_override(config: WizardConfig) -> str:
    """Return docker-compose.override.yml content."""

    def _env_block(pairs: list[tuple[str, str]], indent: str) -> list[str]:
        lines = [f"{indent}environment:"]
        for k, v in pairs:
            lines.append(f"{indent}  {k}: {_yaml_val(v)}")
        return lines

    lines = [
        "# smb-mock docker-compose override — generated by smb-mock wizard",
        "services:",
        "  kdc:",
    ]
    lines += _env_block(_kdc_env(config), "    ")
    lines += [
        "  samba:",
    ]
    lines += _env_block(_samba_env(config), "    ")
    return "\n".join(lines) + "\n"
